name = "bn9-api"
main = "./src/index.ts"
compatibility_date = "2026-02-01"

[[d1_databases]]
binding = "DB"
database_name = "bn9_db"
database_id = "PUT_YOUR_DATABASE_ID_HERE"

[triggers]
crons = ["* * * * *"]
